version: '3.1'

services:

  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_LOGIN
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_LOGIN:$MONGO_PASSWORD@mongo:27017/